name = "MyLib"
uuid = "12345678-1234-1234-1234-123456789012"
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
LinearAlgebra = "1.11.0"
NamedArrays = "0.10.5"
Serialization = "1.11.0"
SparseArrays = "1.11.0"
